chore(dev-deps): ⬆️ update devdependencies (non-major) (patch) (#8)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@ianvs/prettier-plugin-sort-imports](https://togithub.com/ianvs/prettier-plugin-sort-imports) | [`^3.7.1` -> `^3.7.2`](https://renovatebot.com/diffs/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.1/3.7.2) | [![age](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/compatibility-slim/3.7.1)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/@ianvs%2fprettier-plugin-sort-imports/3.7.2/confidence-slim/3.7.1)](https://docs.renovatebot.com/merge-confidence/) |
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | [`^2.8.6` -> `^2.8.7`](https://renovatebot.com/diffs/npm/prettier/2.8.6/2.8.7) | [![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/compatibility-slim/2.8.6)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/confidence-slim/2.8.6)](https://docs.renovatebot.com/merge-confidence/) |
| [release-it](https://togithub.com/release-it/release-it) | [`^15.9.1` -> `^15.9.3`](https://renovatebot.com/diffs/npm/release-it/15.9.1/15.9.3) | [![age](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/compatibility-slim/15.9.1)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/release-it/15.9.3/confidence-slim/15.9.1)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>ianvs/prettier-plugin-sort-imports</summary>

### [`v3.7.2`](https://togithub.com/IanVS/prettier-plugin-sort-imports/releases/tag/v3.7.2)

[Compare Source](https://togithub.com/ianvs/prettier-plugin-sort-imports/compare/v3.7.1...v3.7.2)

#### What's Changed

-   Fix importOrderCombineTypeAndValueImports for Flow by [@&#8203;IanVS](https://togithub.com/IanVS) in [https://github.com/IanVS/prettier-plugin-sort-imports/pull/57](https://togithub.com/IanVS/prettier-plugin-sort-imports/pull/57)

**Full Changelog**: https://github.com/IanVS/prettier-plugin-sort-imports/compare/v3.7.1...v3.7.2

</details>

<details>
<summary>prettier/prettier</summary>

### [`v2.8.7`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;287)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

[diff](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

##### Allow multiple decorators on same getter/setter ([#&#8203;14584](https://togithub.com/prettier/prettier/pull/14584) by [@&#8203;fisker](https://togithub.com/fisker))



```ts
// Input
class A {
  @&#8203;decorator()
  get foo () {}
  
  @&#8203;decorator()
  set foo (value) {}
}

// Prettier 2.8.6
SyntaxError: Decorators cannot be applied to multiple get/set accessors of the same name. (5:3)
  3 |   get foo () {}
  4 |   
> 5 |   @&#8203;decorator()
    |   ^^^^^^^^^^^^
  6 |   set foo (value) {}
  7 | }

// Prettier 2.8.7
class A {
  @&#8203;decorator()
  get foo() {}

  @&#8203;decorator()
  set foo(value) {}
}
```

</details>

<details>
<summary>release-it/release-it</summary>

### [`v15.9.3`](https://togithub.com/release-it/release-it/releases/tag/15.9.3)

[Compare Source](https://togithub.com/release-it/release-it/compare/15.9.2...15.9.3)

-   Remove knip from devDependencies as it requires Node.js v16 ([`31e4f4d`](https://togithub.com/release-it/release-it/commit/31e4f4d))

### [`v15.9.2`](https://togithub.com/release-it/release-it/releases/tag/15.9.2)

[Compare Source](https://togithub.com/release-it/release-it/compare/15.9.1...15.9.2)

-   Add knip analysis to release hooks ([`88a06ea`](https://togithub.com/release-it/release-it/commit/88a06ea))
-   Fix up config for Knip v2 ([`b96d1bf`](https://togithub.com/release-it/release-it/commit/b96d1bf))
-   Add --registry argument to `npm publish` if set in `publishConfig.registry` ([`c59d55e`](https://togithub.com/release-it/release-it/commit/c59d55e))
-   Update dependencies ([`7c86856`](https://togithub.com/release-it/release-it/commit/7c86856))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 12am and before 5am every weekday,every weekend" in timezone Asia/Kolkata, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://app.renovatebot.com/dashboard#github/timelessco/node-js-app-template).